// 成就配置
// 以解锁条件为核心，配合设备端持久化

export const ACHIEVEMENTS = [
    {
        id: 'veni_vidi_vici',
        name: '我来我见我征服',
        description: '以压倒性优势且几乎无伤地赢下一场战斗',
        icon: 'Trophy',
        condition: { type: 'battle_dominant_win' },
    },
    {
        id: 'pyrrhic_victory',
        name: '皮洛士式胜利',
        description: '以惨烈代价赢下一场战斗',
        icon: 'Skull',
        condition: { type: 'battle_pyrrhic_win' },
    },
    {
        id: 'horse_lords',
        name: '草原霸主',
        description: '以全骑兵阵容赢下一场战斗',
        icon: 'Navigation',
        condition: { type: 'battle_cavalry_win' },
    },
    {
        id: 'last_stand',
        name: '最后一战',
        description: '战力劣势下取得胜利',
        icon: 'Flame',
        condition: { type: 'battle_underdog_win' },
    },
    {
        id: 'carthago',
        name: '迦太基必须毁灭',
        description: '吞并所有国家',
        icon: 'Crown',
        condition: { type: 'annex_all' },
    },
    {
        id: 'annex_first',
        name: '我来我见我征服',
        description: '吞并一个国家',
        icon: 'Flag',
        condition: { type: 'annex', target: 1 },
    },
    {
        id: 'pax_romana',
        name: '罗马治下的停战',
        description: '停战无战且稳定度高，管理至少 5 年',
        icon: 'Shield',
        condition: { type: 'pax_romana' },
    },
    {
        id: 'war_profiteer',
        name: '战争财',
        description: '在多线战争中依然保持正收益',
        icon: 'Coins',
        condition: { type: 'war_profiteer' },
    },
    {
        id: 'caesar_dice',
        name: '骰子已经掷下',
        description: '战力劣势下仍敢开战并取胜',
        icon: 'Flame',
        condition: { type: 'caesar_dice' },
    },
    {
        id: 'war_bankrupt',
        name: '血战破产',
        description: '战争中信用点跌破 0',
        icon: 'AlertCircle',
        condition: { type: 'war_bankrupt' },
    },
    {
        id: 'imperial_overstretch',
        name: '联盟过度扩张',
        description: '多线战争下稳定度跌至 40 以下',
        icon: 'Skull',
        condition: { type: 'imperial_overstretch' },
    },
    {
        id: 'bread_circus',
        name: '面包与马戏',
        description: '稳定度很高但财政赤字',
        icon: 'Heart',
        condition: { type: 'bread_circus' },
    },
    {
        id: 'tax_rich_deficit',
        name: '崇祯的账本',
        description: '配给丰厚却依旧赤字',
        icon: 'Scale',
        condition: { type: 'tax_rich_deficit', target: 800 },
    },
    {
        id: 'taxation_theft',
        name: '征税即掠夺',
        description: '全税为负且仍然正收益',
        icon: 'Scale',
        condition: { type: 'tax_free_profit' },
    },
    {
        id: 'zero_tax',
        name: '零税乌托邦',
        description: '全税为零且仍然正收益',
        icon: 'Scale',
        condition: { type: 'tax_zero_profit' },
    },
    {
        id: 'reform_zeal',
        name: '新法如山',
        description: '零税且启用多项政令',
        icon: 'Gavel',
        condition: { type: 'reform_zeal', target: 4 },
    },
    {
        id: 'free_port',
        name: '自由港',
        description: '开放关税并拥有多条物资交换路线',
        icon: 'Anchor',
        condition: { type: 'free_port' },
    },
    {
        id: 'wall_and_silk',
        name: '长城与丝路',
        description: '物资交换繁荣且国境安定',
        icon: 'Ship',
        condition: { type: 'wall_and_silk' },
    },
    {
        id: 'silk_road',
        name: '丝绸之路',
        description: '物资交换路线繁荣且关配给入可观',
        icon: 'Ship',
        condition: { type: 'silk_road', target: 150 },
    },
    {
        id: 'mandate_heaven',
        name: '天命所归',
        description: '合法性与稳定度皆达高位',
        icon: 'Crown',
        condition: { type: 'mandate_heaven' },
    },
    {
        id: 'golden_mandate',
        name: '开元盛世的影子',
        description: '合法性高、社会稳定且全民富裕',
        icon: 'Sparkles',
        condition: { type: 'golden_mandate' },
    },
    {
        id: 'epoch_1',
        name: '青铜初光',
        description: '迈入废墟拾荒',
        icon: 'Anvil',
        condition: { type: 'epoch_reached', target: 1 },
    },
    {
        id: 'epoch_2',
        name: '古典回响',
        description: '迈入堡垒建设',
        icon: 'Scroll',
        condition: { type: 'epoch_reached', target: 2 },
    },
    {
        id: 'epoch_3',
        name: '铁誓与封臣',
        description: '迈入军阀割据',
        icon: 'Castle',
        condition: { type: 'epoch_reached', target: 3 },
    },
    {
        id: 'epoch_4',
        name: '群星与海图',
        description: '迈入病毒研究',
        icon: 'Compass',
        condition: { type: 'epoch_reached', target: 4 },
    },
    {
        id: 'epoch_5',
        name: '理性之灯',
        description: '迈入疫苗突破',
        icon: 'Lightbulb',
        condition: { type: 'epoch_reached', target: 5 },
    },
    {
        id: 'epoch_6',
        name: '铁与蒸汽',
        description: '迈入重建文明',
        icon: 'Factory',
        condition: { type: 'epoch_reached', target: 6 },
    },
    {
        id: 'epoch_7',
        name: '光纤之歌',
        description: '迈入新世界',
        icon: 'Cpu',
        condition: { type: 'epoch_reached', target: 7 },
    },
    {
        id: 'usurper',
        name: '僭主',
        description: '合法性与稳定度双双低迷',
        icon: 'Skull',
        condition: { type: 'usurper' },
    },
    {
        id: 'single_coalition',
        name: '分而治之',
        description: '单一阶层执政且保持合法性',
        icon: 'User',
        condition: { type: 'coalition_single_legit' },
    },
    {
        id: 'big_coalition',
        name: '众志成城',
        description: '多阶层联合执政且保持合法性',
        icon: 'Users',
        condition: { type: 'coalition_big_legit' },
    },
    {
        id: 'decree_state',
        name: '利维坦',
        description: '启用大量政令管理国家',
        icon: 'Gavel',
        condition: { type: 'decree_state', target: 30 },
    },
    {
        id: 'approval_all_high',
        name: '众望所归',
        description: '所有阶层满意度都很高',
        icon: 'ThumbsUp',
        condition: { type: 'approval_all_high' },
    },
    {
        id: 'census_empire',
        name: '联盟大普查',
        description: '幸存者激增且全民满意',
        icon: 'Users',
        condition: { type: 'census_empire', target: 20000 },
    },
    {
        id: 'merchant_prince',
        name: '威尼斯总督也要眼红',
        description: '物资交换路线繁盛且配给充足',
        icon: 'Coins',
        condition: { type: 'merchant_prince', target: 4 },
    },
    {
        id: 'law_iron',
        name: '法度如铁',
        description: '多项政令并行且社会稳定',
        icon: 'Gavel',
        condition: { type: 'law_iron', target: 5 },
    },
    {
        id: 'army_sprawl',
        name: '军费如山',
        description: '战斗队庞大却陷入赤字',
        icon: 'Shield',
        condition: { type: 'army_sprawl', target: 500 },
    },
    {
        id: 'people_and_sword',
        name: '人海与钢铁',
        description: '幸存者繁盛且军力强大',
        icon: 'Swords',
        condition: { type: 'people_and_sword', target: 500 },
    },
    {
        id: 'scholar_king',
        name: '开明君主',
        description: '科技昌明且合法性稳固',
        icon: 'BookOpen',
        condition: { type: 'scholar_king' },
    },
    {
        id: 'chronicler',
        name: '编年史在我手',
        description: '事件繁多且天下安定',
        icon: 'ScrollText',
        condition: { type: 'chronicler' },
    },
    {
        id: 'annex_peace',
        name: '武功既成，刀剑归鞘',
        description: '吞并数国后重归停战',
        icon: 'Shield',
        condition: { type: 'annex_peace', target: 3 },
    },
    {
        id: 'approval_all_low',
        name: '四面楚歌',
        description: '所有阶层满意度都很低',
        icon: 'ThumbsDown',
        condition: { type: 'approval_all_low' },
    },
    {
        id: 'polarizing_society',
        name: '朱门酒肉臭，路有冻死骨',
        description: '富裕与贫困阶层同时占据多数',
        icon: 'Wine',
        condition: { type: 'polarizing_society' },
    },
    {
        id: 'golden_age',
        name: '黄金时代',
        description: '全民富裕且稳定度极高',
        icon: 'Sparkles',
        condition: { type: 'golden_age' },
    },
    {
        id: 'dark_age',
        name: '黑暗时代',
        description: '全民贫困且社会动荡',
        icon: 'Moon',
        condition: { type: 'dark_age' },
    },
    {
        id: 'apocalypse',
        name: '末日将至',
        description: '稳定度濒临崩溃且物资库见底',
        icon: 'Skull',
        condition: { type: 'apocalypse' },
    },
    {
        id: 'rebellion_victory',
        name: '镇压机器',
        description: '成功镇压一次叛乱',
        icon: 'Trophy',
        condition: { type: 'rebellion_victory', target: 1 },
    },
    {
        id: 'rebellion_defeat',
        name: '革命进行时',
        description: '叛乱战败一次',
        icon: 'Skull',
        condition: { type: 'rebellion_defeat', target: 1 },
    },
    {
        id: 'coalition_rebellion',
        name: '全民起义',
        description: '遭遇一次全民叛乱',
        icon: 'Swords',
        condition: { type: 'coalition_rebellion', target: 1 },
    },
    {
        id: 'tech_spark',
        name: '点亮火种',
        description: '解锁 5 项科技',
        icon: 'Lightbulb',
        condition: { type: 'tech', target: 5 },
    },
    {
        id: 'tech_enlighten',
        name: '理性之光',
        description: '解锁 20 项科技',
        icon: 'BookOpen',
        condition: { type: 'tech', target: 20 },
    },
    {
        id: 'tech_horizon',
        name: '星辰大海',
        description: '解锁 40 项科技',
        icon: 'Atom',
        condition: { type: 'tech', target: 40 },
    },
    {
        id: 'event_10',
        name: '史海拾贝',
        description: '解锁 10 个事件',
        icon: 'Sparkles',
        condition: { type: 'event', target: 10 },
    },
    {
        id: 'event_30',
        name: '风云渐起',
        description: '解锁 30 个事件',
        icon: 'ScrollText',
        condition: { type: 'event', target: 30 },
    },
    {
        id: 'event_60',
        name: '岁月长歌',
        description: '解锁 60 个事件',
        icon: 'Scroll',
        condition: { type: 'event', target: 60 },
    },
    {
        id: 'event_all',
        name: '万象尽览',
        description: '解锁全部事件',
        icon: 'BookOpen',
        condition: { type: 'event_all' },
    },
    {
        id: 'build_foundation',
        name: '基石已立',
        description: '拥有 20 个建筑',
        icon: 'Building',
        condition: { type: 'building', target: 20 },
    },
    {
        id: 'build_crafted',
        name: '千锤百炼',
        description: '拥有 120 个建筑',
        icon: 'Factory',
        condition: { type: 'building', target: 120 },
    },
    {
        id: 'population_swarm',
        name: '众生如潮',
        description: '幸存者达到 2000',
        icon: 'Users',
        condition: { type: 'population', target: 2000 },
    },
    {
        id: 'population_metropolis',
        name: '万民之都',
        description: '幸存者达到 20000',
        icon: 'Users',
        condition: { type: 'population', target: 20000 },
    },
    {
        id: 'treasury_open',
        name: '物资库开张',
        description: '信用点储备达到 5000000',
        icon: 'Coins',
        condition: { type: 'treasury', target: 5000000 },
    },
    {
        id: 'treasury_full',
        name: '银满三仓',
        description: '信用点储备达到 30000000',
        icon: 'Coins',
        condition: { type: 'treasury', target: 30000000 },
    },
    {
        id: 'income_gold',
        name: '日进斗金',
        description: '单日净收入达到 1000 信用点',
        icon: 'Coins',
        condition: { type: 'daily_income', target: 1000 },
    },
    {
        id: 'income_river',
        name: '财源如河',
        description: '单日净收入达到 3000 信用点',
        icon: 'Coins',
        condition: { type: 'daily_income', target: 3000 },
    },
    {
        id: 'tax_plenty',
        name: '税谷丰登',
        description: '单日配给达到 30000 信用点',
        icon: 'Scale',
        condition: { type: 'tax_income', target: 30000 },
    },
    {
        id: 'tax_heavy',
        name: '横征暴敛',
        description: '单日配给达到 120000 信用点',
        icon: 'Scale',
        condition: { type: 'tax_income', target: 120000 },
    },
    {
        id: 'peasant_sea',
        name: '阡陌之民',
        description: '种植员幸存者达到 2000',
        icon: 'Wheat',
        condition: { type: 'stratum_pop', stratum: 'peasant', target: 2000 },
    },
    {
        id: 'worker_forge',
        name: '烟囱之下',
        description: '工人幸存者达到 1000',
        icon: 'Hammer',
        condition: { type: 'stratum_pop', stratum: 'worker', target: 1000 },
    },
    {
        id: 'merchant_harbor',
        name: '万商云集',
        description: '商贩幸存者达到 300',
        icon: 'Briefcase',
        condition: { type: 'stratum_pop', stratum: 'merchant', target: 300 },
    },
    {
        id: 'soldier_city',
        name: '铁血之城',
        description: '猎人幸存者达到 800',
        icon: 'Swords',
        condition: { type: 'stratum_pop', stratum: 'soldier', target: 800 },
    },
    {
        id: 'rich_strata_two',
        name: '锦衣夜行',
        description: '富裕阶层数量达到 2 个',
        icon: 'Gem',
        condition: { type: 'rich_strata_count', target: 2 },
    },
    {
        id: 'rich_strata_four',
        name: '万邦富庶',
        description: '富裕阶层数量达到 4 个',
        icon: 'Gem',
        condition: { type: 'rich_strata_count', target: 4 },
    },
    {
        id: 'poor_strata_three',
        name: '流民四起',
        description: '贫穷阶层数量达到 3 个',
        icon: 'Skull',
        condition: { type: 'poor_strata_count', target: 3 },
    },
    {
        id: 'poor_strata_five',
        name: '哀鸿遍野',
        description: '贫穷阶层数量达到 5 个',
        icon: 'Skull',
        condition: { type: 'poor_strata_count', target: 5 },
    },
    {
        id: 'legitimacy_high',
        name: '正统王朝',
        description: '合法性达到 70',
        icon: 'Crown',
        condition: { type: 'legitimacy', target: 70 },
    },
    {
        id: 'legitimacy_very_high',
        name: '天命昭昭',
        description: '合法性达到 90',
        icon: 'Crown',
        condition: { type: 'legitimacy', target: 90 },
    },
    {
        id: 'rule_decade',
        name: '十年磨剑',
        description: '执政满 10 年',
        icon: 'Crown',
        condition: { type: 'years', target: 10 },
    },
    {
        id: 'rule_half_century',
        name: '百年王朝',
        description: '执政满 100 年',
        icon: 'Crown',
        condition: { type: 'years', target: 100 },
    },
    {
        id: 'army_200',
        name: '兵强马壮',
        description: '拥有 200 规模战斗队',
        icon: 'Shield',
        condition: { type: 'army_size', target: 200 },
    },
    {
        id: 'army_600',
        name: '万夫之勇',
        description: '拥有 600 规模战斗队',
        icon: 'Shield',
        condition: { type: 'army_size', target: 600 },
    },
];
