/**
 * 生存科技树配置 - 丧尸文明：末日崛起
 * 每个科技包含：
 * - id: 科技唯一标识
 * - name: 科技名称
 * - desc: 科技描述和效果
 * - cost: 研究成本
 * - epoch: 解锁时代
 */
export const TECHS = [
    // 末日降临
    {
        id: 'barter',
        name: "以物易物",
        desc: "允许建造交易站，开启幸存者间的物资交换。财政收入 +2%。",
        cost: { science: 150 },
        epoch: 0,
        effects: { incomePercent: 0.02 },
    },
    {
        id: 'stone_axes',
        name: "自制武器",
        desc: "拆卸站产出提升 25%。",
        cost: { science: 150 },
        epoch: 0,
        effects: { buildings: { lumber_camp: 0.12 } },
    },
    {
        id: 'flint_knapping',
        name: "废墟搜索",
        desc: "废墟矿场效率增加 25%。",
        cost: { science: 210 },
        epoch: 0,
        effects: { buildings: { quarry: 0.12 } },
    },
    {
        id: 'animal_husbandry',
        name: "末日求生",
        desc: "学会在废墟中觅食，每人每日额外获得 0.1 罐头。",
        cost: { science: 240 },
        epoch: 0,
        effects: { perPopPassive: { food: 0.1 } },
    },
    {
        id: 'pottery',
        name: "物资储存",
        desc: "菜地储存效率 +10%。",
        cost: { science: 300 },
        epoch: 0,
        effects: { buildings: { farm: 0.05 } },
    },
    {
        id: 'tool_making',
        name: "废品利用",
        desc: "解锁简易工坊。搜索建筑效率 +10%。",
        cost: { science: 270 },
        epoch: 0,
        effects: { categories: { gather: 0.05 } },
    },
    {
        id: 'basic_irrigation',
        name: "灌溉系统",
        desc: "建造灌溉系统，菜地产量提升 15%。",
        cost: { science: 360 },
        epoch: 0,
        effects: { buildings: { farm: 0.08 } },
    },
    {
        id: 'oral_tradition',
        name: "求生手册",
        desc: "编写求生手册，信号站效率提升 15%。",
        cost: { science: 330 },
        epoch: 0,
        effects: { buildings: { library: 0.08 } },
    },
    {
        id: 'communal_granary',
        name: "物资储备",
        desc: "幸存者容量 +10%。",
        cost: { science: 390 },
        epoch: 0,
        effects: { maxPop: 0.1 },
    },

    {
        id: 'river_fishing',
        name: "陷阱捕猎",
        desc: "每人每日额外获得 0.05 罐头，收入 +1%。",
        cost: { science: 450 },
        epoch: 0,
        effects: { perPopPassive: { food: 0.05 }, incomePercent: 0.01 },
    },
    {
        id: 'wheel',
        name: "推车",
        desc: "搜索建筑整体效率 +20%。",
        cost: { science: 480 },
        epoch: 0,
        effects: { categories: { gather: 0.1 } },
    },

    // 废墟拾荒
    {
        id: 'sailing',
        name: "车队运输",
        desc: "解锁车队基地，开启长途物资搜索。收入 +3%。",
        cost: { science: 1050 },
        epoch: 1,
        effects: { incomePercent: 0.03, perPopPassive: { food: 0.02 } },
    },
    {
        id: 'tools',
        name: "改良工具",
        desc: "允许建造材料加工厂，工业效率 +5%。",
        cost: { science: 750 },
        epoch: 1,
        effects: { categories: { industry: 0.03 } },
    },
    {
        id: 'copper_mining',
        name: "电子设备回收",
        desc: "解锁电池回收站。",
        cost: { science: 840 },
        epoch: 1,
        effects: {},
    },
    {
        id: 'bronze_working',
        name: "金属回收",
        desc: "回收铸造坊产出 +30%，汽车坟场 +15%。",
        cost: { science: 960 },
        epoch: 1,
        effects: { buildings: { bronze_foundry: 0.15, mine: 0.08 } },
    },
    {
        id: 'horse_collar',
        name: "耕种改良",
        desc: "菜地与农场增产 10%。",
        cost: { science: 780 },
        epoch: 1,
        effects: { buildings: { farm: 0.05, large_estate: 0.05 } },
    },
    {
        id: 'caravan_trade',
        name: "商队网络",
        desc: "交换站信用点收入 +35%。",
        cost: { science: 900 },
        epoch: 1,
        effects: { buildings: { market: 0.18 } },
    },
    {
        id: 'granary_architecture',
        name: "仓库加固",
        desc: "物资仓库 +25%，幸存者容量 +5%。",
        cost: { science: 960 },
        epoch: 1,
        effects: { buildings: { granary: 0.12 }, maxPop: 0.05 },
    },
    {
        id: 'primitive_weaving',
        name: "急救培训",
        desc: "学习急救知识。急救站效率 +10%。",
        cost: { science: 820 },
        epoch: 1,
        effects: { buildings: { loom_house: 0.05 } },
    },
    {
        id: 'early_administration',
        name: "基础管理",
        desc: "解锁管理站，建立物资分配体系。启用管理者系统。",
        cost: { science: 880 },
        epoch: 1,
        effects: { categories: { civic: 0.05 } },
    },

    // 堡垒建设
    {
        id: 'papyrus_cultivation',
        name: "情报网络",
        desc: "情报站效率 +20%。",
        cost: { science: 1575 },
        epoch: 2,
        effects: { buildings: { reed_works: 0.12 } },
    },
    {
        id: 'culinary_arts',
        name: "肉类加工",
        desc: "解锁肉类加工坊。",
        cost: { science: 1680 },
        epoch: 2,
        effects: {},
    },
    {
        id: 'brewing',
        name: "净水技术",
        desc: "解锁净水站，提供洁净饮用水。",
        cost: { science: 1610 },
        epoch: 2,
        effects: {},
    },
    {
        id: 'carpentry',
        name: "装甲制造",
        desc: "解锁装甲工坊，制造防护装备。",
        cost: { science: 1750 },
        epoch: 2,
        effects: {},
    },
    {
        id: 'library_catalogs',
        name: "数据分析",
        desc: "信号站研究 +25%。",
        cost: { science: 1645 },
        epoch: 2,
        effects: { buildings: { library: 0.15 } },
    },
    {
        id: 'amphitheater_design',
        name: "娱乐策划",
        desc: "解锁娱乐中心。",
        cost: { science: 1470 },
        epoch: 1,
        effects: {},
    },
    {
        id: 'urban_planning',
        name: "安全区规划",
        desc: "板房效率 +20%，幸存者容量 +5%。",
        cost: { science: 1820 },
        epoch: 2,
        effects: { buildings: { house: 0.12 }, maxPop: 0.05 },
    },
    {
        id: 'republican_code',
        name: "避难所公约",
        desc: "公约提升避难所运转效率。民生建筑效率 +15%。",
        cost: { science: 1960 },
        epoch: 2,
        effects: { categories: { civic: 0.09 }, maxPop: 0.05 },
    },
    {
        id: 'road_system',
        name: "补给路线",
        desc: "搜索效率 +10%。",
        cost: { science: 2100 },
        epoch: 2,
        effects: { categories: { gather: 0.06 } },
    },
    {
        id: 'advanced_weaving',
        name: "高级急救",
        desc: "改进急救技术。急救站效率 +20%。",
        cost: { science: 1950 },
        epoch: 2,
        effects: { buildings: { loom_house: 0.12 } },
    },

    // 军阀割据
    {
        id: 'feudalism',
        name: "区域制度",
        desc: "农场效率 +15%。",
        cost: { science: 3500 },
        epoch: 3,
        effects: { buildings: { large_estate: 0.09 } },
    },
    {
        id: 'basic_weaving',
        name: "医疗设备",
        desc: "新型医疗设备。急救站效率 +25%。",
        cost: { science: 3150 },
        epoch: 3,
        effects: { buildings: { loom_house: 0.15 } },
    },
    {
        id: 'theology',
        name: "心理辅导",
        desc: "广播塔士气产出 +30%。",
        cost: { science: 3850 },
        epoch: 3,
        effects: { buildings: { church: 0.18 } },
    },
    {
        id: 'bureaucracy',
        name: "组织管理",
        desc: "解锁指挥中心。搜索、工业、民生建筑效率 +5%。管理者容量 +3。",
        cost: { science: 4200 },
        epoch: 3,
        effects: { categories: { gather: 0.03, industry: 0.03, civic: 0.03 }, perPopPassive: { culture: 0.002 } },
    },
    {
        id: 'civil_service',
        name: "人事管理",
        desc: "系统化的管理人员选拔。收入 +5%，管理者容量 +3。",
        cost: { science: 8750 },
        epoch: 4,
        effects: { incomePercent: 0.05 },
    },
    {
        id: 'administrative_reform',
        name: "管理改革",
        desc: "改革管理体系。民生效率 +10%，管理者容量 +4。",
        cost: { science: 18900 },
        epoch: 5,
        effects: { categories: { civic: 0.07 } },
    },
    {
        id: 'centralization',
        name: "统一指挥",
        desc: "统一指挥链。收入 +8%，管理者容量 +2。",
        cost: { science: 27900 },
        epoch: 6,
        effects: { incomePercent: 0.08 },
    },
    {
        id: 'three_field_system',
        name: "轮作制度",
        desc: "菜地和农场 +15% 产量。",
        cost: { science: 3850 },
        epoch: 3,
        effects: { buildings: { farm: 0.09, large_estate: 0.09 } },
    },
    {
        id: 'stone_keep_engineering',
        name: "加固工程",
        desc: "居住建筑容量 +10%。",
        cost: { science: 4025 },
        epoch: 3,
        effects: { buildings: { hut: 0.06, house: 0.06 } },
    },
    {
        id: 'manor_architecture',
        name: "掩体工程",
        desc: "解锁混凝土掩体。效率 +15%，容量 +5%。",
        cost: { science: 4550 },
        epoch: 3,
        effects: { buildings: { manor_house: 0.15 }, maxPop: 0.05 },
    },
    {
        id: 'monastic_brewing',
        name: "工业净水",
        desc: "解锁大型净水厂。效率 +15%，广播塔 +10%。",
        cost: { science: 4200 },
        epoch: 3,
        effects: { buildings: { monastery_cellar: 0.15, church: 0.10 } },
    },
    {
        id: 'wool_trade',
        name: "医疗生产",
        desc: "解锁医疗工厂。效率 +15%，急救站 +10%。",
        cost: { science: 3850 },
        epoch: 3,
        effects: { buildings: { wool_workshop: 0.15, loom_house: 0.10 } },
    },
    {
        id: 'masonry_guild',
        name: "拆解工会",
        desc: "解锁废墟拆解场。效率 +15%，矿场 +10%。",
        cost: { science: 4025 },
        epoch: 3,
        effects: { buildings: { stone_workshop: 0.15, quarry: 0.10 } },
    },
    {
        id: 'forestry_management',
        name: "拆卸管理",
        desc: "解锁大型拆卸场。效率 +15%，拆卸站 +10%。",
        cost: { science: 3675 },
        epoch: 3,
        effects: { buildings: { hardwood_camp: 0.15, lumber_camp: 0.10 } },
    },

    {
        id: 'ritual_priesthood',
        name: "宣传学",
        desc: "礼拜设施士气产出提升 15%。",
        cost: { science: 1190 },
        epoch: 3,
        effects: { buildings: { church: 0.09 } },
    },
    {
        id: 'ironworking',
        name: "金属锻造",
        desc: "解锁铁匠铺，汽车坟场效率 +30%。",
        cost: { science: 1500 },
        epoch: 2,
        effects: { buildings: { mine: 0.18 } },
    },
    // 病毒研究
    {
        id: 'cartography',
        name: "区域勘探",
        desc: "车队基地搜索 +25%。",
        cost: { science: 6300 },
        epoch: 4,
        effects: { buildings: { dockyard: 0.18 } },
    },
    {
        id: 'charter_companies',
        name: "贸易协议",
        desc: "贸易港信用点 +30%，收入 +5%。",
        cost: { science: 6650 },
        epoch: 4,
        effects: { buildings: { trade_port: 0.21 }, incomePercent: 0.05 },
    },
    {
        id: 'navigator_schooling',
        name: "侦察术",
        desc: "侦察学院研究 +30%。",
        cost: { science: 7000 },
        epoch: 4,
        effects: { buildings: { navigator_school: 0.21 } },
    },
    {
        id: 'naval_artillery',
        name: "火力测试",
        desc: "车队基地额外 +15%。",
        cost: { science: 7350 },
        epoch: 4,
        effects: { buildings: { dockyard: 0.10 } },
    },
    {
        id: 'colonial_ledgers',
        name: "探索档案",
        desc: "系统化的殖民地档案管理，提升海外贸易效率。船坞和贸易港效率 +20%，财政收入 +5%。",
        cost: { science: 7700 },
        epoch: 4,
        effects: { buildings: { dockyard: 0.14, trade_port: 0.14 }, incomePercent: 0.05 },
    },
    {
        id: 'spice_monopolies',
        name: "物资垄断",
        desc: "贸易港再获 15% 产量。",
        cost: { science: 8050 },
        epoch: 4,
        effects: { buildings: { trade_port: 0.10 } },
    },
    {
        id: 'colonial_architecture',
        name: "集装箱改造",
        desc: "解锁集装箱社区。效率 +15%，容量 +5%。",
        cost: { science: 8400 },
        epoch: 4,
        effects: { buildings: { townhouse: 0.15 }, maxPop: 0.05 },
    },
    {
        id: 'new_world_dyes',
        name: "新药研发",
        desc: "解锁高级药剂室。效率 +15%，药剂室 +10%。",
        cost: { science: 7875 },
        epoch: 4,
        effects: { buildings: { dye_workshop: 0.15, dye_works: 0.10 } },
    },

    // 疫苗突破

    {
        id: 'coffee_agronomy',
        name: "药草种植",
        desc: "解锁药草园。",
        cost: { science: 14400 },
        epoch: 5,
        effects: {},
    },
    {
        id: 'coffeehouse_philosophy',
        name: "学术交流",
        desc: "解锁研究沙龙。",
        cost: { science: 15300 },
        epoch: 5,
        effects: { perPopPassive: { culture: 0.002 } },
    },
    {
        id: 'printing_press',
        name: "无线电通讯",
        desc: "解锁通讯中心。",
        cost: { science: 16200 },
        epoch: 5,
        effects: {},
    },
    {
        id: 'public_schooling',
        name: "生存教育",
        desc: "信号站 +25% 研究。",
        cost: { science: 17100 },
        epoch: 5,
        effects: { buildings: { library: 0.18 }, perPopPassive: { culture: 0.001 } },
    },
    {
        id: 'social_contract',
        name: "幸存者公约",
        desc: "公约提升社会效率。民生效率 +20%，容量 +5%。",
        cost: { science: 18000 },
        epoch: 5,
        effects: { categories: { civic: 0.14 }, maxPop: 0.05, perPopPassive: { culture: 0.003 } },
    },
    {
        id: 'salon_debates',
        name: "文艺复兴",
        desc: "剧场士气再增 15%。",
        cost: { science: 18900 },
        epoch: 5,
        effects: { buildings: { amphitheater: 0.10 } },
    },
    {
        id: 'enlightened_urbanism',
        name: "地下工程",
        desc: "解锁地下堡垒。效率 +15%，容量 +6%。",
        cost: { science: 19800 },
        epoch: 5,
        effects: { buildings: { civic_apartment: 0.15 }, maxPop: 0.06 },
    },

    // 重建文明
    {
        id: 'coal_gasification',
        name: "燃油提炼",
        desc: "解锁油库。",
        cost: { science: 23400 },
        epoch: 6,
        effects: {},
    },
    {
        id: 'steel_alloys',
        name: "合金配方",
        desc: "解锁合金冶炼厂。",
        cost: { science: 24300 },
        epoch: 6,
        effects: {},
    },
    {
        id: 'industrialization',
        name: "工业重建",
        desc: "解锁军工厂，工业效率 +10%。",
        cost: { science: 27000 },
        epoch: 6,
        effects: { categories: { industry: 0.07 } },
    },
    {
        id: 'steam_power',
        name: "电力恢复",
        desc: "工业建筑 +20% 产量。",
        cost: { science: 28800 },
        epoch: 6,
        effects: { categories: { industry: 0.14 } },
    },
    {
        id: 'chemical_fertilizer',
        name: "生物肥料",
        desc: "菜地与农场 +20% 产出。",
        cost: { science: 27000 },
        epoch: 6,
        effects: { buildings: { farm: 0.14, large_estate: 0.14 } },
    },
    {
        id: 'rail_network',
        name: "公路网",
        desc: "运输枢纽效率 +30%，搜索 +10%。",
        cost: { science: 27900 },
        epoch: 6,
        effects: { buildings: { rail_depot: 0.21 }, categories: { gather: 0.07 } },
    },
    {
        id: 'precision_tools',
        name: "精密武器",
        desc: "军工厂产出 +25%。",
        cost: { science: 28800 },
        epoch: 6,
        effects: { buildings: { factory: 0.18 } },
    },

    // 战斗科技
    {
        id: 'military_training',
        name: "战斗训练",
        desc: "解锁训练营，提供战斗容量。战斗效率 +15%。",
        cost: { science: 2800 },
        epoch: 2,
        effects: { categories: { military: 0.10 } },
    },
    {
        id: 'fortification',
        name: "防御工事",
        desc: "解锁防御工事。战斗效率 +25%，容量 +5%。",
        cost: { science: 8400 },
        epoch: 4,
        effects: { categories: { military: 0.18 }, maxPop: 0.05 },
    },

    // ========== 高级工业科技 ==========

    // 纺织产业升级科技
    {
        id: 'mechanized_weaving',
        name: "自动医疗",
        desc: "解锁织布坊和成衣作坊，水力驱动的飞梭织机大幅提升绷带产量。织布坊效率 +20%，成衣作坊效率 +15%。",
        cost: { science: 13500 },
        epoch: 5,
        effects: { buildings: { loom_house: 0.14, tailor_workshop: 0.10 } },
    },
    {
        id: 'assembly_line',
        name: "批量生产",
        desc: "解锁纺织厂和服装工厂，标准化分工使产量大幅提升。纺织厂效率 +25%，服装工厂效率 +20%。",
        cost: { science: 26100 },
        epoch: 6,
        effects: { buildings: { textile_mill: 0.18, garment_factory: 0.14 } },
    },

    // 废材加工产业升级科技
    {
        id: 'hydraulic_sawing',
        name: "电动工具",
        desc: "解锁锯木厂和伐木场升级，水轮驱动的圆锯效率远超手工。锯木厂效率 +25%，伐木场效率 +15%。",
        cost: { science: 12600 },
        epoch: 5,
        effects: { buildings: { sawmill: 0.18, lumber_camp: 0.10 } },
    },
    {
        id: 'mass_production',
        name: "大规模生产",
        desc: "解锁废材加工厂和装甲板工坊，标准化零件实现批量生产。废材加工厂效率 +20%，装甲板工坊效率 +25%。",
        cost: { science: 25200 },
        epoch: 6,
        effects: { buildings: { lumber_mill: 0.14, furniture_workshop: 0.18 } },
    },

    // 冶金产业升级科技
    {
        id: 'advanced_metallurgy',
        name: "先进冶金",
        desc: "解锁竖井矿场，改良熔炉与合金配方提升工具质量。铁器铺效率 +20%，青铜铸坊效率 +15%。",
        cost: { science: 7700 },
        epoch: 4,
        effects: { buildings: { iron_tool_workshop: 0.14, bronze_foundry: 0.10 } },
    },
    {
        id: 'bessemer_process',
        name: "电弧冶炼",
        desc: "解锁炼钢厂和冶金工坊，吹入空气快速去碳，钢铁产量剧增。炼钢厂效率 +30%，冶金工坊效率 +25%。",
        cost: { science: 27900 },
        epoch: 6,
        effects: { buildings: { steel_foundry: 0.21, metallurgy_workshop: 0.18 } },
    },

    // 建材产业升级科技
    {
        id: 'industrial_ceramics',
        name: "工业零件",
        desc: "解锁砖窑升级，环形窑与传送带实现连续烧制。砖窑效率 +25%。",
        cost: { science: 11700 },
        epoch: 5,
        effects: { buildings: { brickworks: 0.18 } },
    },
    {
        id: 'standardized_construction',
        name: "模块化建筑",
        desc: "解锁建材厂，预制构件加速建设、降低成本。建材厂效率 +25%，幸存者上限 +5%。",
        cost: { science: 24300 },
        epoch: 6,
        effects: { buildings: { building_materials_plant: 0.18 }, maxPop: 0.05 },
    },

    // 食品加工产业升级科技
    {
        id: 'food_preservation',
        name: "食品保鲜",
        desc: "解锁罐头厂，密封罐装技术延长食品保质期。",
        cost: { science: 22500 },
        epoch: 6,
        effects: { buildings: { culinary_kitchen: 0.18 } },
    },
    {
        id: 'distillation',
        name: "蒸馏净水",
        desc: "解锁蒸馏酒厂，分离提纯出高度烈酒。",
        cost: { science: 14400 },
        epoch: 5,
        effects: { buildings: { brewery: 0.21 } },
    },

    // 造纸印刷产业升级科技
    {
        id: 'wood_pulp_process',
        name: "数据采集",
        desc: "解锁造纸厂，废材纤维取代手工纸浆，产量倍增。",
        cost: { science: 13050 },
        epoch: 5,
        effects: { buildings: { reed_works: 0.21 } },
    },
    {
        id: 'mass_media',
        name: "大众通讯",
        desc: "解锁印刷所和出版社，报纸杂志覆盖全民，舆论力量崛起。印刷所效率 +30%，出版社效率 +20%。",
        cost: { science: 24750 },
        epoch: 6,
        effects: { buildings: { printing_house: 0.21, publishing_house: 0.14 } },
    },

    // 高级采集科技
    {
        id: 'deep_shaft_mining',
        name: "深层挖掘",
        desc: "解锁工业矿场，蒸汽泵排水、铁轨运矿，开采深层矿脉。",
        cost: { science: 23400 },
        epoch: 6,
        effects: { buildings: { mine: 0.18, coal_mine: 0.14 } },
    },
    {
        id: 'agricultural_machinery',
        name: "农业机械",
        desc: "解锁机械化农场，蒸汽拖拉机与收割机解放大量人力。",
        cost: { science: 25200 },
        epoch: 6,
        effects: { buildings: { farm: 0.18, large_estate: 0.21 } },
    },
    {
        id: 'steam_logging',
        name: "机械拆卸",
        desc: "解锁伐木公司，蒸汽锯与窄轨铁路运输原木。",
        cost: { science: 22500 },
        epoch: 6,
        effects: { buildings: { lumber_camp: 0.21 } },
    },

    // 高级士气与城市科技
    {
        id: 'higher_education',
        name: "高级研究",
        desc: "解锁大学，系统化培养专业人才。",
        cost: { science: 15750 },
        epoch: 5,
        effects: { buildings: { library: 0.14, navigator_school: 0.14 } },
    },
    {
        id: 'grand_arts',
        name: "士气复兴",
        desc: "解锁歌剧院，戏剧与音乐的殿堂。",
        cost: { science: 17100 },
        epoch: 5,
        effects: { buildings: { amphitheater: 0.18, church: 0.10 } },
    },
    {
        id: 'urban_architecture',
        name: "城市重建",
        desc: "解锁公寓楼，多层建筑容纳更多城市幸存者。幸存者上限 +6%。",
        cost: { science: 26100 },
        epoch: 6,
        effects: { buildings: { house: 0.14 }, maxPop: 0.06 },
    },
    {
        id: 'financial_capitalism',
        name: "贸易联盟",
        desc: "解锁证券交易所，股票与债券调配社会资本。贸易港效率 +20%，铁路枢纽效率 +15%，财政收入 +8%。",
        cost: { science: 29250 },
        epoch: 6,
        effects: { buildings: { trade_port: 0.14, rail_depot: 0.10 }, incomePercent: 0.08 },
    },
];
